# Generated by Django 5.2.15 on 2026-06-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=200)),
                ('chunk_index', models.IntegerField()),
                ('embedding', models.TextField()),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='capsules.capsule')),
            ],
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE capsules_documentchunk ALTER COLUMN embedding TYPE vector USING embedding::vector;",
            reverse_sql="ALTER TABLE capsules_documentchunk ALTER COLUMN embedding TYPE text USING embedding::text;"
        ),
    ]
