# Generated by Django 5.2.15 on 2026-06-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='suggested_questions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CapsuleAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hash', models.CharField(max_length=64)),
                ('unanswered_text', models.TextField(blank=True, default='')),
                ('was_answered', models.BooleanField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='capsules.capsule')),
            ],
        ),
    ]
