# Generated by Django 5.2.15 on 2026-06-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0003_capsule_suggested_questions_capsuleanalytic'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='custom_accent_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='capsule',
            name='custom_logo_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
