# Generated by Django 5.2.15 on 2026-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_tag_capsule_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
