# Generated by Django 5.2.15 on 2026-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0007_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='capsules/'),
        ),
    ]
